name: qoe_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.0
  gap: ^3.0.1
  hugeicons: ^0.0.10
  path_provider: ^2.1.5
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  dart_ping: ^9.0.1
  flutter_signal_strength: ^0.0.1
  supabase_flutter: ^2.9.1
  device_info_plus: ^11.5.0
  sim_card_info: ^1.0.2
  provider: ^6.1.5
  mobile_number: ^3.0.0
  get_ip_address: ^0.0.7
  network_type_detector: ^1.0.1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.6
  flutter_internet_speed_test: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

